#!/bin/bash

# Arbitrary but unique message tag
msgTag="dunstbrightness"

max_brightness=$(brightnessctl m)
brightness_step=$(echo "scale=2; $max_brightness/100*$2" | bc)
brightness_step=$(printf "%.0f" $brightness_step)

if [[ "$1" == "-inc" ]]; then
    brightnessctl s $brightness_step+
elif [[ "$1" == "-dec" ]]; then
    brightnessctl s $brightness_step-
elif [[ "$1" == "-set" ]]; then
    brightnessctl s $brightness_step
fi

brightness=$(brightnessctl g)
brightness=$(echo "scale=2; 100/$max_brightness*$brightness" | bc)
brightness=$(printf "%.0f" $brightness)

icon="display-brightness-symbolic"

dunstify -i $icon -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$brightness" -t 800 "Brightness: $brightness"
